---
apiVersion: v1
kind: Pod
metadata:
  name: swiss-army-knife
spec:
  securityContext:
    runAsUser: 65534
    runAsGroup: 65534
    runAsNonRoot: true
    fsGroup: 65534
  containers:
  - name: swiss-army-knife
    image: fsschmitt/swiss-army-knife:latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      allowPrivilegeEscalation: false
    command:
      - sleep
    args: ["infinity"]
